services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symf_app
    environment:
      APP_ENV: dev
      APP_SECRET: 00000000000000000000000000000000
      DATABASE_URL: "postgresql://app:app@db:5432/app?serverVersion=16&charset=utf8"
      REDIS_URL: "redis://redis:6379"
      COMPOSER_ALLOW_SUPERUSER: "1"
    depends_on:
      - db
      - redis
    ports:
      - "8080:8000"
    volumes:
      - ./:/app_overlay:ro

  db:
    image: postgres:16-alpine
    container_name: symf_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "app"]
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: symf_redis

volumes:
  db_data:
