parameters:
  app.default_page_size: 20

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\EventSubscriber\RequestIdSubscriber:
    tags: ['kernel.event_subscriber']

  App\EventListener\TaskCreatedListener:
    tags:
      - { name: 'kernel.event_listener', event: 'App\Event\TaskCreatedEvent', method: 'onTaskCreated' }
